package project.swingcalculator;

import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.text.NumberFormat;
import java.util.ArrayList;
import java.util.Locale;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

public class CurrencyConverter extends javax.swing.JFrame {

    private DecimalFormatSymbols simbolos = new DecimalFormatSymbols(Locale.getDefault());
    private DecimalFormat formatoMoneda = new DecimalFormat("#,##0.00", simbolos);
    private double valueToConvert = 0;
    private CAD cad = new CAD();
    private COP cop = new COP();
    private EUR eur = new EUR();
    private MNX mnx = new MNX();
    private USD usd = new USD();
    private DefaultComboBoxModel exchangeModel1 = new DefaultComboBoxModel();
    private DefaultComboBoxModel exchangeModel2 = new DefaultComboBoxModel();
    private ArrayList<Integer> lastNumber = new ArrayList<Integer>();
    private int dotAmount = 0;

    public CurrencyConverter() {
        initComponents();
        setVisible(true);
        setLocationRelativeTo(null);
        simbolos.setCurrencySymbol(""); // Establecer el símbolo de moneda como cadena vacía
        fillCurrencyModel();
        cbCurrency1.setSelectedItem(cop);
        cbCurrency2.setSelectedItem(usd);
    }

    ;

    public void fillCurrencyModel() {
        exchangeModel1.addElement(cad);
        exchangeModel1.addElement(cop);
        exchangeModel1.addElement(eur);
        exchangeModel1.addElement(mnx);
        exchangeModel1.addElement(usd);

        exchangeModel2.addElement(cad);
        exchangeModel2.addElement(cop);
        exchangeModel2.addElement(eur);
        exchangeModel2.addElement(mnx);
        exchangeModel2.addElement(usd);

    }

    ;
    
    public double convert(double value, ICurrency m1, ICurrency m2) {
        return value * m2.getCurrencyExchange() / m1.getCurrencyExchange();
    }

    ;

    public void buttonMethod(int i) {
        if (valueToConvert < 10000000) {
            if(dotAmount==0){
                valueToConvert = valueToConvert * 10 + i;
                lastNumber.add(i);
            } else {
                valueToConvert = valueToConvert + (i /Math.pow(10, dotAmount));
                dotAmount++;
                System.out.println(valueToConvert);
            }

        } else {
            JOptionPane.showMessageDialog(null, "Number too big");
        }

        lblValue1.setText(formatoMoneda.format(valueToConvert));
    }

    ;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        rootPanel = new javax.swing.JPanel();
        lblValue1 = new javax.swing.JLabel();
        cbCurrency1 = new javax.swing.JComboBox<>();
        lblValue2 = new javax.swing.JLabel();
        cbCurrency2 = new javax.swing.JComboBox<>();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btn0 = new javax.swing.JButton();
        btnDot = new javax.swing.JButton();
        btnC = new javax.swing.JButton();
        btnErase = new javax.swing.JButton();
        lblCurrency1 = new javax.swing.JLabel();
        lblCurrency2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        modeMenu = new javax.swing.JMenu();
        calculatorItem = new javax.swing.JMenuItem();
        moneyConverterItem = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        exitItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Currency Converter");
        setMinimumSize(new java.awt.Dimension(280, 400));

        rootPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                rootPanelMouseReleased(evt);
            }
        });
        rootPanel.setLayout(new java.awt.GridBagLayout());

        lblValue1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblValue1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblValue1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblValue1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                lblValue1PropertyChange(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.2;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(10, 20, 5, 10);
        rootPanel.add(lblValue1, gridBagConstraints);

        cbCurrency1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbCurrency1.setModel(exchangeModel1);
        cbCurrency1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCurrency1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 10);
        rootPanel.add(cbCurrency1, gridBagConstraints);

        lblValue2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblValue2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblValue2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.2;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(10, 20, 5, 10);
        rootPanel.add(lblValue2, gridBagConstraints);

        cbCurrency2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbCurrency2.setModel(exchangeModel2);
        cbCurrency2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCurrency2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 10, 10);
        rootPanel.add(cbCurrency2, gridBagConstraints);

        btn1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btn1.setText("1");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        rootPanel.add(btn1, gridBagConstraints);

        btn2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btn2.setText("2");
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        rootPanel.add(btn2, gridBagConstraints);

        btn3.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btn3.setText("3");
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        rootPanel.add(btn3, gridBagConstraints);

        btn4.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btn4.setText("4");
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        rootPanel.add(btn4, gridBagConstraints);

        btn5.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btn5.setText("5");
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        rootPanel.add(btn5, gridBagConstraints);

        btn6.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btn6.setText("6");
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        rootPanel.add(btn6, gridBagConstraints);

        btn7.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btn7.setText("7");
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        rootPanel.add(btn7, gridBagConstraints);

        btn8.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btn8.setText("8");
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        rootPanel.add(btn8, gridBagConstraints);

        btn9.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btn9.setText("9");
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        rootPanel.add(btn9, gridBagConstraints);

        btn0.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btn0.setText("0");
        btn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn0ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        rootPanel.add(btn0, gridBagConstraints);

        btnDot.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btnDot.setText(".");
        btnDot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDotActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        rootPanel.add(btnDot, gridBagConstraints);

        btnC.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btnC.setText("C");
        btnC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        rootPanel.add(btnC, gridBagConstraints);

        btnErase.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btnErase.setText("E");
        btnErase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEraseActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        rootPanel.add(btnErase, gridBagConstraints);

        lblCurrency1.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        lblCurrency1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCurrency1.setText("$");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        rootPanel.add(lblCurrency1, gridBagConstraints);

        lblCurrency2.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        lblCurrency2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCurrency2.setText("$");
        lblCurrency2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        rootPanel.add(lblCurrency2, gridBagConstraints);

        modeMenu.setText("Mode");

        calculatorItem.setText("Calculator");
        calculatorItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculatorItemActionPerformed(evt);
            }
        });
        modeMenu.add(calculatorItem);

        moneyConverterItem.setText("Currency Converter");
        moneyConverterItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moneyConverterItemActionPerformed(evt);
            }
        });
        modeMenu.add(moneyConverterItem);
        modeMenu.add(jSeparator1);

        exitItem.setText("Exit");
        exitItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitItemActionPerformed(evt);
            }
        });
        modeMenu.add(exitItem);

        jMenuBar1.add(modeMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rootPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rootPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 377, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Ventanas
    private void calculatorItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculatorItemActionPerformed
        dispose();
        Calculator calculator = new Calculator();
    }//GEN-LAST:event_calculatorItemActionPerformed

    private void moneyConverterItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moneyConverterItemActionPerformed

    }//GEN-LAST:event_moneyConverterItemActionPerformed

    private void exitItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitItemActionPerformed

    // Botones Signos
    private void btnCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCActionPerformed
        valueToConvert = 0;
        lblValue1.setText("");
        lblValue2.setText("");
        dotAmount = 0;
    }//GEN-LAST:event_btnCActionPerformed

    private void btnEraseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEraseActionPerformed
        valueToConvert = (valueToConvert - (lastNumber.get(lastNumber.size() - 1))) / 10;
        lastNumber.remove(lastNumber.size() - 1);
        lblValue1.setText(formatoMoneda.format(valueToConvert));
        dotAmount = 0;
    }//GEN-LAST:event_btnEraseActionPerformed

    private void btnDotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDotActionPerformed
        dotAmount++;
        System.out.println(dotAmount);
    }//GEN-LAST:event_btnDotActionPerformed

    // Botones Numeros
    private void btn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn0ActionPerformed
        buttonMethod(0);
    }//GEN-LAST:event_btn0ActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        buttonMethod(1);
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        buttonMethod(2);
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        buttonMethod(3);
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        buttonMethod(4);
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        buttonMethod(5);
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        buttonMethod(6);
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        buttonMethod(7);
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        buttonMethod(8);
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        buttonMethod(9);
    }//GEN-LAST:event_btn9ActionPerformed

    //listeners
    private void rootPanelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rootPanelMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_rootPanelMouseReleased

    private void lblValue1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_lblValue1PropertyChange
        lblValue1.setText(formatoMoneda.format(valueToConvert));
        if (cbCurrency1.getSelectedItem() != null && cbCurrency2.getSelectedItem() != null) {
            lblValue2.setText(formatoMoneda.format(convert(valueToConvert, (ICurrency) cbCurrency1.getSelectedItem(), (ICurrency) cbCurrency2.getSelectedItem())));
        }
    }//GEN-LAST:event_lblValue1PropertyChange

    private void cbCurrency1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCurrency1ActionPerformed
        if (cbCurrency1.getSelectedItem() != null && cbCurrency2.getSelectedItem() != null) {
            lblValue2.setText(formatoMoneda.format(convert(valueToConvert, (ICurrency) cbCurrency1.getSelectedItem(), (ICurrency) cbCurrency2.getSelectedItem())));
        }
    }//GEN-LAST:event_cbCurrency1ActionPerformed

    private void cbCurrency2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCurrency2ActionPerformed
        if (cbCurrency1.getSelectedItem() != null && cbCurrency2.getSelectedItem() != null) {
            lblValue2.setText(formatoMoneda.format(convert(valueToConvert, (ICurrency) cbCurrency1.getSelectedItem(), (ICurrency) cbCurrency2.getSelectedItem())));
        }
    }//GEN-LAST:event_cbCurrency2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CurrencyConverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CurrencyConverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CurrencyConverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CurrencyConverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CurrencyConverter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnC;
    private javax.swing.JButton btnDot;
    private javax.swing.JButton btnErase;
    private javax.swing.JMenuItem calculatorItem;
    private javax.swing.JComboBox<String> cbCurrency1;
    private javax.swing.JComboBox<String> cbCurrency2;
    private javax.swing.JMenuItem exitItem;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JLabel lblCurrency1;
    private javax.swing.JLabel lblCurrency2;
    private javax.swing.JLabel lblValue1;
    private javax.swing.JLabel lblValue2;
    private javax.swing.JMenu modeMenu;
    private javax.swing.JMenuItem moneyConverterItem;
    private javax.swing.JPanel rootPanel;
    // End of variables declaration//GEN-END:variables

}
